config:
  profile: default
  message: default test
  
spring:
  datasource:
    hikari:
      maximum-pool-size: 2
    driverClassName: "net.sf.log4jdbc.sql.jdbcapi.DriverSpy"
    url: "jdbc:log4jdbc:mariadb://172.0.0.1:3306/TESTDB"
    username: "default"
    password: "1234"