config:
  profile: test
  message: test test
  
  
spring:
  datasource:
    hikari:
      maximum-pool-size: 2
    driverClassName: "net.sf.log4jdbc.sql.jdbcapi.DriverSpy"
    url: "jdbc:log4jdbc:mariadb://172.0.0.1:3308/TESTDB"
    username: "tester"
    password: "1234"  